# Generated by Django 4.0.2 on 2022-02-19 15:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='debt',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
