# Generated by Django 4.0.2 on 2022-02-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0002_person_debt_person_email_person_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.CharField(choices=[('T', 'Triangle'), ('S', 'Square'), ('C', 'Circle')], default='C', max_length=1)),
                ('salary', models.PositiveIntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Suit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], default='M', max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('colour', models.CharField(choices=[('G', 'Green'), ('R', 'Red')], default='R', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='recruitment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.CharField(choices=[('D', 'Dead'), ('A', 'Alive')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='person',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='debt',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unknown')], default=('U', 'Unknown'), max_length=1),
        ),
    ]
