# Generated by Django 4.0.2 on 2022-02-20 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0003_guard_suit_person_height_person_recruitment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='recruitment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.CharField(choices=[('A', 'Alive'), ('D', 'Dead')], default='A', max_length=1),
        ),
    ]
