# Generated by Django 4.0.2 on 2022-02-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0004_alter_person_recruitment_date_alter_person_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guard',
            name='rank',
            field=models.CharField(choices=[('S', 'Square'), ('T', 'Triangle'), ('C', 'Circle')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='recruitment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
