# Generated by Django 4.0.2 on 2022-02-20 10:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0006_person_number_alter_guard_rank_alter_person_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guard',
            name='rank',
            field=models.CharField(choices=[('T', 'Triangle'), ('C', 'Circle'), ('S', 'Square')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.CharField(choices=[('D', 'Dead'), ('A', 'Alive')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='suit',
            name='colour',
            field=models.CharField(choices=[('G', 'Green'), ('R', 'Red')], default='R', max_length=1),
        ),
    ]
